### ISSUE TITLE
Enhancement - support more alert notifiers out-of-the box

### ISSUE THREAD

**Issue by henrikjohansen** [humio/issues#10]
Currently Humio comes with build-in alert notifiers for email, slack and generic webhooks. You should really support some of the major player for alert management (PagerDuty, OpsGenie, VictorOps) to make alerts a more pleasent experience for users.

**Comment by anagrius** [comment]
Which would you say are the most important?

The ones you mention are: PagerDuty, OpsGenie, VictorOps

In that order?

**Comment by anagrius** [comment]
If you have already written a webhook for them you can just post them here and we might save some time implementing it ourselves.

**Comment by henrikjohansen** [comment]
Yes, in that order :) We have something for OpsGenie - see [their API docs](https://docs.opsgenie.com/v1.0/docs/alert-api#section-create-alert) for examples :)

**Comment by geeters** [comment]
Hi guys,

We have been in contact with them directly, so I can do intros to their engineering team.  They would like this too, the OpsGenie folks.
-best
g

**Comment by anagrius** [comment]
@henrikjohansen It would be interesting to know a little more about which options/fields would be the most useful to support. The API's have lots of options, e.g. teams, actions, tags, you name it.

Which features would be the essential ones, which would most generally useful, etc.
