### ISSUE TITLE
Event order does not switch when toggle button pushed

### ISSUE THREAD

**Issue by forewarned** [humio/issues#101]
After running a live search query with a function (such as timechart), I select the "events" tab. The toggle button to switch the order of events based on time does not affect the order. My profile default is set to put newest events at the top.

* Humio Version:1.6.2--build-7074--sha-1f9b4fd66
* Browser Version: Chrome 77.0.3865.90
* API
* Query Examples
* Screenshots
![image](https://user-images.githubusercontent.com/14337073/65457639-3bbfac80-de09-11e9-9a25-1a3d9fca568e.png)
The button circled in the screenshot above does not work.
* Videos

**Comment by andejens** [comment]
Closing this issue as fixed.
