### ISSUE TITLE
Rename Dashboard Functionality Broken

### ISSUE THREAD

**Issue by forewarned** [humio/issues#103]
Steps to reproduce:
Dashboards >> Select the three dots menu on an existing dashboard >> Rename

A box appears, but the whole GUI seems to stop working and the user never gets a chance to actually rename the dashboard or proceed past the box.

A work-around is to open the dashboard and edit the name from there.

* Humio Version: 1.6.2--build-7074--sha-1f9b4fd66
* Browser Version: Google Chrome 77.0.3865.120 (Official Build) (64-bit)
* API NA
* Query Examples NA
* Screenshots
![image](https://user-images.githubusercontent.com/14337073/66864591-bbe1b980-ef52-11e9-9cdb-ed1621f6776e.png)

* Videos

**Comment by andejens** [comment]
Hi @forewarned thank you for letting us know - we will take a look.

**Comment by KasMA1990** [comment]
This is fixed in Humio 1.6.3 🙂

**Comment by andejens** [comment]
closing issue as fixed in 1.6.3.
