### ISSUE TITLE
Annoying browser compatibility warning, false positive

### ISSUE THREAD

**Issue by wknapik** [humio/issues#105]
Humio Version: Humio Cloud v1.6.5
Browser Version: Brave Browser 78.0.70.122 (Linux)
--
I'm getting this annoying warning in bright red saying

> Your browser version is not supported by Humio. As a result you may broken functionality and visual errors.
> We recommend using one of the following browsers for the best experience:
Edge (Macos): >=77, Edge (Windows): >=18, Safari: >=12.1, Chrome: >=60, Firefox: >=65

My browser is based on Chromium and works perfectly fine with Humio, so all the warning does is annoy me every time I go to cloud.humio.com. Please fix the "compatibility" detection, or remove the warning altogether.

This all smacks of the old "This website is best viewed in Internet Explorer 6 in 800x600 resolution". I thought those days were behind us...

**Comment by andejens** [comment]
Thank you - we will take a look

**Comment by andejens** [comment]
Hi @wknapik we have been looking into reproducing this without any luck.
Could you do us a favour and return us your user-agent? E.g. by using this tool:
https://developers.whatismybrowser.com/useragents/parse/
Then click the "your own user agent" and tell us what result you are getting. This will help us a lot in  our troubleshooting.

**Comment by wknapik** [comment]
Hi @andejens,

Now I can't reproduce this myself either. I did upgrade the browser and various extensions since reporting the issue though.

Brave on Linux will normally present a user agent like
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
```
but I do normally spoof it, in which case it would be something like
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
```

Neither of these produce the error message anymore.

FWIW, I think looking at the user agent is wrong, since anyone can present any ua string they like and there are [good reasons](https://panopticlick.eff.org/) to spoof it, but it's up to you. Feel free to resolve this issue.

Thanks,
WK

**Comment by andejens** [comment]
OK - got it, thank you for your feedback.
