### ISSUE TITLE
Memory Leak on Dashboard running Live Queries

### ISSUE THREAD

**Issue by forewarned** [humio/issues#109]
When a dashboard running live queries is left open, its memory usage increases. Even when the page is refreshed, the memory is not cleared. After a day or two, I have to close and reopen the browser tab to clear the used memory.

After about 24 hours, a dashboard was using 1.2GB RAM. After closing and reopening the tab, it only consumed 134MB of RAM.

* Humio Version: 1.6.10--build-9955--sha-1f958b7bef
* Browser Version Google Chrome 79.03945.79 (Official Build) (64-bit)
* API
* Query Examples
* Screenshots
* Videos

**Comment by andejens** [comment]
Hi @forewarned thank you for reporting this issue - we'll take a look.
What kind of widgets do you have on your dashboard?

**Comment by anagrius** [comment]
Thanks. We are aware of the issue. We are planning on releasing a new implementation of charts soon. This issue should disappear at that point.
