### ISSUE TITLE
The changelog for Humio Cloud is not parsed as markdown in the webui

### ISSUE THREAD

**Issue by wknapik** [humio/issues#113]
* Humio Version
Humio Cloud Release v1.11.0
* Browser Version
Brave Browser 81.1.8.96

The release information, which appears to be written using markdown, is not parsed as markdown and ends up being displayed as plain text, making it really difficult to read.

![humio-release-info](https://user-images.githubusercontent.com/1129003/82828126-af421e00-9eb0-11ea-848a-1bab7193c0cd.png)

**Comment by andejens** [comment]
Hi @wknapik yes - this isn't exactly great - we are working on making this easer to read.

**Comment by jfmengels** [comment]
Hi @wknapik :wave: 

This issue has been fixed on Humio Cloud v1.12.0. Thank you for reporting this issue!

**Comment by wknapik** [comment]
Thanks!
