### ISSUE TITLE
Feature Request - suspending / stopping a dataspace

### ISSUE THREAD

**Issue by henrikjohansen** [humio/issues#14]
In certain scenarios it could be very beneficial if a dataspace could be suspended or stopped. In practice this should make Humio stop accepting ingest events for that dataspace until it got started / unsuspended.

**Comment by krestenkrab** [comment]
This is not too easy to do.  We can reject a dataspace at the HTTP level (if that's what you're asking), but once data has been accepted, it is mixed up in the ingest queue with other data sources that happen to go to the same shard.

**Comment by henrikjohansen** [comment]
The primary reason is to stop ingest (ie. stop accepting more data) - I am aware that once data is in Kafka is will be processed. This could be used while testing or if a certain dataspace should start to misbehave.

**Comment by mortengrouleff** [comment]
There is a "**Block Ingest**" tab in settings on a repository that will make Humio reject ingest events on HTTP with 503, and pause any ingest listeners on TCP/UDP as well.
