### ISSUE TITLE
Feature Request - allow multiple notifiers for an alert

### ISSUE THREAD

**Issue by henrikjohansen** [humio/issues#22]
Currently a single alert can only trigger a single notifier - sometimes you need more than that (like pushing a message into a Slack channel and sending an email to create a ticket) ... Humio should support that usecase.

**Comment by Crevil** [comment]
We have the same use case. A Slack message and Pager Duty trigger for the same query would be nice.

**Comment by mwl** [comment]
And eventually parametized them as well?

**Comment by floekke** [comment]
Mats from sparebank: "we are probably mostly going to configure it from the API and occasionally UI"

**Comment by anagrius** [comment]
Closing. This is part of an upcoming release.
