### ISSUE TITLE
Link function that generate web links in the web view

### ISSUE THREAD

**Issue by mwl** [humio/issues#25]
Would be really nice if we could insert links in `table`s and `groupby`s, i.e. something like

```
link("https://mesosmaster/#/services/detail/" + mesos_service_id, "open in DCOS", as=service_link)
| table([mesos_service_id, service_link])
```

Function arguments would be something like

| Name | Type | Is required | Default value | Description|
|------|------|-------------|---------------|------------|
| href | String| true       |               | A valid url |
| label | String | false    | Open          | Label for the link |
| target | String | false   |               | `A` tag target attribute |
| as   | String | false     |               | The output name of the field to round (defaults to the same as the input field) |

**Comment by henrikjohansen** [comment]
👍 +1

**Comment by krestenkrab** [comment]
Fixed?

**Comment by henrikjohansen** [comment]
Yes.

**Comment by deejgregor** [comment]
👍 +1 as well

**Comment by pmech** [comment]
this is fixed. Closing.

**Comment by krestenkrab** [comment]
The "fix" we have is that a value that looks like a URL will be displayed as a clickable link.  There is no `link` function, and no way to say something mark-down'ish `[text](link)`.  Mayhaps we should simply recognise such a value (where the link part is a URL) and display the text as the label of the link.
