### ISSUE TITLE
Feature Request - Show fields in sidebar

### ISSUE THREAD

**Issue by Crevil** [humio/issues#27]
It could be great if the "Show fields" list could be displayed as a sidebar. This avoids the excessive amount of whitespace between the three columns and makes more space for the logs.

* Humio Version
Version: 2017-11-16T08-50-16--build-1204--sha-f15c4e367ee62e187f76788c12eb0feb3181be0e

* Screeshots
![screen shot 2017-12-15 at 11 07 43](https://user-images.githubusercontent.com/6881694/34039120-b78c306e-e18e-11e7-8409-9790b12b791b.png)

**Comment by anagrius** [comment]
I agree.
