### ISSUE TITLE
Feature Request: Grafana Datasource supporting proxy access mode

### ISSUE THREAD

**Issue by kaspernissen** [humio/issues#28]
We are heavy users of Grafana as a dashboarding tool. We use it for gathering metrics from our different systems, mostly Prometheus, and previously Elasticsearch. 

We would like to be able to query Humio from Grafana. 

We know that you are already working on this, but we are missing the option of communicating using the `proxy` access mode internally.

**Comment by pmech** [comment]
Hi Kasper. Thank for putting this in. We will look into this, this year, or early next year.
