### ISSUE TITLE
When "expanding" a dashboard, the dashboard titlebar gets hidden

### ISSUE THREAD

**Issue by Jesper84** [humio/issues#33]
* Humio Version: 2017-12-18T13-59-11--build-1480--sha-c3d4e89c0a646a940b7ef846257918f4baf6f987
* Browser Version: Safari 11.0.2

When expanding the dashboard using the "expand" button shown here:
![screen shot 2017-12-19 at 10 56 33](https://user-images.githubusercontent.com/472491/34151390-57d6d816-e4ab-11e7-93ad-c02ea5381d4b.png)

The dashboard titlebar is hidden under the "normal" menubar, which now is unresponsive.
Seems like som z-index related issue...
![screen shot 2017-12-19 at 10 57 32](https://user-images.githubusercontent.com/472491/34151430-7633e0d8-e4ab-11e7-8084-23a74929a9d9.png)

**Comment by pmech** [comment]
Thanks Jesper. We'll look into this.

**Comment by anagrius** [comment]
@Jesper84 Thanks for the heads-up. Fixed on master. Will be part of the next release. It was indeed z-index issue.

**Comment by Jesper84** [comment]
Awesome... you guys work fast!
