### ISSUE TITLE
Persist global time in url on dashboards

### ISSUE THREAD

**Issue by Crevil** [humio/issues#39]
When exploring dashboards I regularly use the global time option. When diving into results, e.g. clicking a link in a table widget, the global time settings is lost when returning to the dashboard.

I use the browser history navigation, so when the setting is not persisted in the URL it will be lost. 
In the search module it's great that the search time selector is persisted. It allows for sharing result easily and if we could get the same for dashboards that would be a great addition.

* Humio Version
`2018-01-19T07-37-48--build-1755--sha-9b1daf191d2625da9a557078cb0af2d6a8413b7f`
* Browser Version
Google Chrome 63.0.3239.132

**Comment by pmech** [comment]
I think we will look into this rather soon. @anagrius will this fit the other changes you are making to dashboards?

**Comment by anagrius** [comment]
Hi, yes that is coming soon.

**Comment by anagrius** [comment]
This is implemented.
