### ISSUE TITLE
Feature Request - dedicated ingest nodes for Humio 

### ISSUE THREAD

**Issue by henrikjohansen** [humio/issues#4]
Currently Humio has a single node type - when operating a larger cluster or having a more complicated network infrastructure I would be beneficial to have nodes that could be dedicated for handling ingest of events. Also this would provide surge protection as a sudden increase in ingest event would not destabilize the entire cluster.

An ingest node should : 
- be able to receive data for all possible ingest methods (HTTP API, Elastic Bulk,TCP/UDP, etc)
- should persist the received data as early and quickly as possible.

From a resilience perspective parsing should first happen when Humio reads from the humio-ingest topic - this is to avoid loosing events in the event of poorly written parsers, etc.

**Comment by krestenkrab** [comment]
By means of our ingest / data sharing mechanism you can actually configure this already today.  But I agree that we should create some admin UI that makes this easy to do.

**Comment by henrikjohansen** [comment]
Until some admin UI exists it could be beneficial to document exactly how to do this.

**Comment by anagrius** [comment]
@krestenkrab Can we close this with the advent of digest nodes?

**Comment by camilleacey** [comment]
Not sure why this wasn't closed. Closing.
