### ISSUE TITLE
Sign up to demo.humio.com is not possible

### ISSUE THREAD

**Issue by kirchner** [humio/issues#47]
When trying to sign in to demo.humio.com using Github and Firefox 59.0.2, the following window opens up:

![snapshot](https://user-images.githubusercontent.com/3667885/44108059-899abd22-9ff9-11e8-8419-30e175ff9fd7.png)

The same also happens in Chrome (64.0.3282.167).

**Comment by pmech** [comment]
Thanks a lot for reporting this. We'll look into this as soon as possible

**Comment by chvitved** [comment]
Again thanks for reporting. It is fixed now
