### ISSUE TITLE
Feature-request: Auto-adjust span if too small

### ISSUE THREAD

**Issue by sbktrifork** [humio/issues#49]
If you have a dashboard showing grafs for a short time range (example "last 1h") and hard-coded span time (example 5 sec), you currently can't use the dashboard filter to extend the time range for all grafs to for example 24h - all grafs will show the ASCII-art owl, because the span is too small.  

Proposal for a fix:
Auto-adjust the span and show the grafs instead of showing the ACSCII-art owl. Perhaps a little warning pop-up to inform the user that the span has been increased. 

* 1.1.21--build-3748--sha-400e9cbf0
* Safari 11.1.2

**Comment by pmech** [comment]
hi @sbktrifork. The `timechart()` function has a `bucket` parameter where you set how many buckets you want in you chart. This parameter is zoom neutral. Will this solve you problem?

**Comment by sbktrifork** [comment]
hi @pmech - that's nice to know, thanks - I will adjust all our dashboards.... 

But I still think that auto-adjusting span if buckets would result in >1500 would be a nice feature. It just doesn't seem user-friendly to end up in a error like this:
"using a span of 50s results in 1728 buckets. Maximum is 1500"
When humio as well just could show the graf with buckets=1500 instead with a little note about the span is too small. 
On the other hand there might be other use-cases (which I'm not aware of) where it makes sense to show the error message instead of returning best-effort-results...  ?

**Comment by mortengrouleff** [comment]
Implemented. When too many buckets would result from the span, the span is widened to fit the max of 1500 buckets, and than a warning is added.
This helps when applying a "global timespan" on a dashboard of widgets with different spans in their charts.
