### ISSUE TITLE
Feature Request - cross dataspace search

### ISSUE THREAD

**Issue by henrikjohansen** [humio/issues#5]
Currently search is restricted to a single dataspace which is inefficient for many use-cases. It should really be possible to search across multiple (or all) dataspaces.

It should be possible to search in : 

- multiple, selected dataspaces
- all dataspaces

**Comment by mortengrouleff** [comment]
Work around: Create a view for the dataspaces and search that.

Providing a "global" view that lets you search all repositories that you are allowed to search is viable but currently conflicts with the name-spacing of saved queries to each view.
