### ISSUE TITLE
S3 Archiving - Sandbox - Error

### ISSUE THREAD

**Issue by jlathrop** [humio/issues#50]
I realize Sandbox is not designed to be a production repo but wanted to pass on this error / bug.  This was discovered as we were trying to implement (still with no success) S3 Archiving on our production repos. 

Sandbox > Settings > S3 Archiving> Enter info and hit save.  
Error `Dict.fromList [("repositoryName","Repository sandbox not found.")]`

* Humio Version: 1.1.27--build-4069--sha-3d275b145
* Browser Version - Firefox 63.0

![s3_archiving_error](https://user-images.githubusercontent.com/5107873/47618184-57052900-da8d-11e8-8b37-4410d434aea1.png)

**Comment by anagrius** [comment]
Thanks for reporting this. And the other bugs! It is super helpful!

This is fixed now, and should be deployed soon. Proof ;) ->

<img width="1226" alt="screenshot 2018-11-08 at 00 33 05" src="https://user-images.githubusercontent.com/157210/48168102-528f0a80-e2ee-11e8-95bf-8702b5427c55.png">
