### ISSUE TITLE
Upload files button does not work

### ISSUE THREAD

**Issue by forewarned** [humio/issues#56]
After navigating to the "Files" page in a repo, clicking the "+" icon on the "BETA" line then clicking "Upload file" does not do anything.

Humio Version: 1.1.33--build-4285--sha-8df21cc92
Browsers: Chrome Version 70.0.3538.110 (Official Build) (64-bit); Firefox 63.0.3 (64-bit)
![image](https://user-images.githubusercontent.com/14337073/49235136-9d181a00-f3b6-11e8-9901-8472ef6e4d43.png)

**Comment by chvitved** [comment]
Thanks for reporting. We have started work on fixing it.

**Comment by anagrius** [comment]
@forewarned I am fixing this now. Sorry about the delay.

**Comment by anagrius** [comment]
I was able to reproduce once, and only in cloud not locally. It seems the file is uploaded correctly even if it gives an error. It might be some sort of race condition.

@forewarned Can you reproduce consistently? Any help is appreciated.

**Comment by forewarned** [comment]
@anagrius This started working in a later Humio update, although I am unsure which version exactly. Right now it works pretty consistently on Humio Version: 1.2.4--build-4637--sha-b575a512d. I would say the original bug I reported is fixed.
