### ISSUE TITLE
Cancel Search Button Repeats Search

### ISSUE THREAD

**Issue by forewarned** [humio/issues#57]
After starting a query then clicking the "Cancel Search" button, sometimes an error will appear saying "Failed to fetch query results." In some cases, the search will begin again and in extreme cases it will keep looping every time the button is clicked.

* Humio Version: 1.2.0--build-4488--sha-f4fc94e32
* Browser Version: Chrome 70.0.3538.110 (Official Build) (64-bit)
* Query Example: Below is a query of the more extreme case the behavior is observed over a large data set in a 4 hour window.
```
#path=conn 
| cidr(id.orig_h, subnet=[<4 subnets>]) | cidr(id.resp_h, subnet=[<4 subnets>])
|!cidr(id.orig_h, subnet=[<1 subnet>]) | !match("file.csv", column=IPAddress, field=id.orig_h, include=[]) 
| groupby(id.orig_h, function=count(id.resp_h,distinct=true))  
 | sort() | rename(field=_count, as=UniqueIPs)
```
* Screeshots
![image](https://user-images.githubusercontent.com/14337073/50025326-5de6ed00-ffa2-11e8-93d0-b3781d886480.png)

**Comment by chvitved** [comment]
Thanks for reporting. We will look into it
