### ISSUE TITLE
When selecting a time from the timestamp field, it adds it to the search in the human readable time which doesn't work. It should add it as epoch.

### ISSUE THREAD

**Issue by jfraiberg** [humio/issues#59]
I was told it human readable just for the "fields" section, but it is actually in epoch.

**Comment by mwl** [comment]
Thanks for reporting @jfraiberg. Could you provide us with some screenshots of the steps to reproduce this issue?

**Comment by jfraiberg** [comment]
When I click on a specific timestamp field from the fields list it adds it to the search like this which does not return any results - 

@timestamp = "1545227439668 (2018-12-19 08:50:39.668)"

That doesn't work unless you change it to - 

@timestamp = "1545227439668"

**Comment by Chadtech** [comment]
Hey @jfraiberg , I just merged a fix for this one. Thanks for reporting it.
