### ISSUE TITLE
When using a filter, the cursor disappears if you are at the end of the filter text. 

### ISSUE THREAD

**Issue by jfraiberg** [humio/issues#60]
You can't tell you are there unless you hit backspace and it removes the last letter.  This is in chrome.

**Comment by mwl** [comment]
Thanks for reporting @jfraiberg. We will look into this straight away. In the meantime could you please provide us with a screenshot so we can confirm we're seeing the same thing?

**Comment by jfraiberg** [comment]
Here is a screenshot of normal behavior, you can see that I have the cursor after the "a" in failed, I see it blinking, etc..:

![cursor_1](https://user-images.githubusercontent.com/24301650/50234696-403fcc00-0384-11e9-8580-3135ae28eea9.PNG)

Here I have moved my cursor to the end of the line after the "d" in failed, but there is no cursor, no blinking line:

![cursor_2](https://user-images.githubusercontent.com/24301650/50234741-58175000-0384-11e9-859a-13a7d34e74fa.PNG)


Here is me hitting backspace where there was no cursor (you will see that the "d" got removed):

![cursor_3](https://user-images.githubusercontent.com/24301650/50234790-754c1e80-0384-11e9-8268-b84b08797863.PNG)

**Comment by Chadtech** [comment]
Hey @jfraiberg 

We havent been able to reproduce this error. Ive tried in different browsers and on different operating systems. Are you still experiencing it? Do notice any conditions you experience it under? Do experience it only on the dashboard page, or also on the search page? What operating system and browser are you using it?

**Comment by chvitved** [comment]
Closing as this should be fixed. @jfraiberg Please reopen if you experience it again
