### ISSUE TITLE
WorldMap normalization flag not applied on dashboard widget

### ISSUE THREAD

**Issue by forewarned** [humio/issues#69]
When creating a WorldMap dashboard widget with the "Normalize Magnitude" checkbox marked, the setting does not stay applied when viewed or accessed on a dashboard.

* Humio Version: Humio Version: 1.2.4--build-4637--sha-b575a512d
* Browser Version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* API
* Query Examples
* Screeshots
![image](https://user-images.githubusercontent.com/14337073/51694116-506b4c80-1fbd-11e9-938a-698c840050f3.png)
* Videos

**Comment by anagrius** [comment]
This is fixed in our master branch and will be coming out soon
