### ISSUE TITLE
Enhancement - kafka.properties from docs is questionable.

### ISSUE THREAD

**Issue by henrikjohansen** [humio/issues#7]
The [Multi-machine distributed Installation](https://go.humio.com/docs/installation/installation-distributed/index.html) gives some bad advise for configuring Kafka.

> log.retention.bytes=17179869184

This setting controls the maximum size of the log before deleting it and can thus be the cause for data loss if Humio should fall behind ingesting data from Kafka. For that reason 'log.retention.bytes' is normally set to '-1' and a time-based retention policy is used in it's place.

Now you should : 
- remove 'log.retention.bytes' from the advertised kafka.properties file
- either introduce 'log.retention.hours' and have the operator set that according to their demand or stick to the default of 168 hours.

**Comment by chvitved** [comment]
Fixed in next release.
`log.retention.bytes` is not used instead `log.retention.hours=48`
