### ISSUE TITLE
Your email signatures have a broken logo

### ISSUE THREAD

**Issue by rorygibson** [humio/issues#73]
(Viewed with GMail)

<img width="1096" alt="screen shot 2019-03-04 at 12 17 47" src="https://user-images.githubusercontent.com/372469/53733037-9c8c9500-3e77-11e9-87c4-9a1d5c2dffde.png">

**Comment by pmech** [comment]
Hi @rorygibson . Thank you very much. I'll make sure we fix this.

**Comment by pmech** [comment]
Hi again Roy,

Actually, this issue should already have been fixed last night (DK time) :).

Thank you again, for taking the time to report bugs and issues. It means a lot to us.

FYI: We have an open Slack (join via community.humio.com). It is a good place to get a quick answers, either from us or some of our other users. Come join, if Slack is something you use :).

Cheers.
