### ISSUE TITLE
Minor typo in timechart builder

### ISSUE THREAD

**Issue by markuswustenberg** [humio/issues#76]
It looks like a horizontal line to me. ;)

<img width="595" alt="Screenshot 2019-03-19 at 09 59 54" src="https://user-images.githubusercontent.com/141763/54593075-fe2f3080-4a2d-11e9-843c-942899e4a6a6.png">

**Comment by mwl** [comment]
It's all relative… I suppose? But I guess you're right 😀

**Comment by markuswustenberg** [comment]
Depends if you look at the screen sideways. ;)

**Comment by anagrius** [comment]
Fixed :red-face:
