### ISSUE TITLE
Syntax highlighting does not work correctly for regex

### ISSUE THREAD

**Issue by jeppeuber** [humio/issues#77]
The syntax highlighting is not quite right for regexes. See attached screenshot

* Humio Version: 
1.4.5--build-5244--sha-cdb52b696

* Browser Version: 
Google Chrome 72.0.3626.121

* Query Examples: 
`#topic=ledger-storage-gateway "Error handling inbound request." | yarpc.error=/^(?<reason>[^ ]*).*$/ | timechart(reason)`

* Screenshots:
![2019-03-25 at 09 44](https://user-images.githubusercontent.com/8612752/54906137-f0245880-4ee2-11e9-9c8e-d122841fca20.png)

**Comment by pmech** [comment]
Hi @jeppeuber . Thank you for reporting this. We will see if we can correct this.

**Comment by ahe-humio** [comment]
@Chadtech Did you have any success on this? If no, feel free to assign it to me, then I'll fold it in to my longer term plans for improving parser UX.

**Comment by Chadtech** [comment]
I haven't, sorry, but I did find the problem. I'll send you the relevant code. @ahe-humio

**Comment by anagrius** [comment]
Hi, we are closing this. We have made an internal task for it.
