### ISSUE TITLE
Humio web interface sorst of count column sorts value as strings instead of as numbers .

### ISSUE THREAD

**Issue by alexsuh7** [humio/issues#84]
Humio web interface sort of count column sorts value as strings instead of as numbers .
See Screenshot attached 
For example:

If the result of the groupby() query returns three rows in the form (value,count)

("value1" , 5) , ("value2" , 411) ,  ("value3", 3123456)

then sorting by count would produce a list in the following order 
sorted by the string value of the count field

* ("value1" , 5) 
* ("value2" , 411) ,
* ("value3", 3123456)

**what is expected?** 
it is expteced for the rows to be sorted by the numeric  value of the 'count' field
* ("value2" , 3123456) 
* ("value3", 411)
* ("value1" , 5) 
,

* Humio Version
1.5.15--build-6280--sha-041138f0f
* Browser Version
Chrome 74 on Windows 10
Version 74.0.3729.169 (Official Build) (64-bit)
* API
Web interface of Hosted Humio 
* Query Examples
level=WARN or level=ERROR | groupby(message)
* Screnshots
![humio-bug](https://user-images.githubusercontent.com/20045918/59259167-eee10d00-8c41-11e9-8d7c-bb0b0cfe4f53.PNG)

**Comment by Chadtech** [comment]
Hello! Thank you for your detailed report of this. This is very clearly related to a recent change I made and I should be able to fix this problem soon. I will post updates here.

**Comment by alexsuh7** [comment]
thanks , good luck 👍

**Comment by Chadtech** [comment]
I've fixed it. I expect it will appear in our next release.

**Comment by mortengrouleff** [comment]
Released in 1.5.16.

**Comment by alexsuh7** [comment]
great , thank you!
