### ISSUE TITLE
Unable to login via 'SignIn with bitBucket'

### ISSUE THREAD

**Issue by alexsuh7** [humio/issues#85]
When trying to login to Humio cloud via 'SignIn with BitBucket' Button 
An Error is shown and login fails

Sign-in failed due to an error
Unexpected response from BitBucket: {&quot;type&quot;: &quot;error&quot;, &quot;error&quot;: {&quot;message&quot;: &quot;Resource removed&quot;, &quot;detail&quot;: &quot;This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https:&#x2F;&#x2F;developer.atlassian.com&#x2F;cloud&#x2F;bitbucket&#x2F;deprecation-notice-v1-apis&#x2F;&quot;}}
![h-bb](https://user-images.githubusercontent.com/20045918/59333612-62961f00-8d01-11e9-97e2-68c99e05464a.png)

* Humio Version
 1.5.16--build-6312--sha-d53a5ff63
* Browser Version
Chrome Win 10

**Comment by pmech** [comment]
Hi @alexsuh7 

Thank you very much for reporting this.
We have just deployed a fix and are very sorry for the trouble this has give you.

Can you confirm that you have access again?

Kind regards,

  -- Peter Mechlenborg

**Comment by alexsuh7** [comment]
Hi @pmech , 

Works great , 

thank you
