### ISSUE TITLE
Links in emails generated by alerts don't point to humio.com and get blocked by adblockers

### ISSUE THREAD

**Issue by wknapik** [humio/issues#92]
Humio Cloud Version: 1.6.2-RC1--build-7308--sha-ce20cefa7

Links in email alerts point to click.pstmrk.it, which uBlock Origin rightly blocks for me (depends on block lists used). I don't want to whitelist that domain. Please change to direct links to humio.com.

**Comment by andejens** [comment]
We'll take a look at this.

**Comment by ssboisen** [comment]
We have disabled link tracking and urls should now point to humio.com directly.

**Comment by andejens** [comment]
Perfect - thank you.

**Comment by wknapik** [comment]
Thanks!
