### ISSUE TITLE
Parser editor: Examples view buggy with many (>30) fields

### ISSUE THREAD

**Issue by gwtwod** [humio/issues#96]
Humio Version: Humio Version: 1.6.3--build-7700--sha-89765c301 (and 1.6.2)
Browser Version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)

In the parser-editor, if you add an example with many fields (>25 or so) the key-value view that pops up when you execute the tests or click on the example event takes up all the space so you can't see the buttons or example list anymore. Only way to get back is to reload the page.

For example, run parseJson() on this event:
```json
{"timestamp":"2019-09-13T14:44:09+0200","clientip":"10.0.0.1","frontend_host":"frontend01","uri":"/api/rss/atom","uri_query":"","method":"GET","status":"200","useragent":"-","referer":"-","session_id":"-","accept_language":"-","ident":"-","user":"-","bytes":"5588","accept_encoding":"-","duration":"9032","cookie":"-","access-requests":"GET /api/rss/atom HTTP/1.1","field1":"value1","field2":"value2","field3":"value3","field4":"value4","field5":"value5","field6":"value6","field7":"value7","field8":"value8","field9":"value9"}
```

**Comment by andejens** [comment]
Thank you for reporting this - we'll take a look.

**Comment by anagrius** [comment]
Fixed, coming out soon
